[package]
name = "rust-template"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
